### ISSUE TITLE
Downloading hash

### ISSUE THREAD

**Issue by caievelyn** [rundel/learnrhash#2]
Is there an easier way for students to download the submission hash?

Right now, I have two text boxes underneath the "Generate Submission" box that asks for students' names and hashes. The idea is that they enter their name into the first box and copy-paste their hash into the second box. Next, they will press "Submit", which creates a dataframe of 2 variables: their name and their hash. Lastly, they will press "Download," which downloads an .rds file that is ready to be uploaded to Canvas. 

Is there any way to simplify this? For example, for there to be a button in which students can generate and directly download the submission hash in one step? I am concerned that students could copy and paste each others' hashes.

**Comment by rundel** [comment]
It should be possible to create a download version of things - I hadn't thought about that approach but it makes sense.

As for the uploading each other's hash - you can include a question in the learnr tutorial that asks them for their name - I did not include one in the example as there is no default learnr question that does not mark a submission and it felt weird to include a name field that returned "wrong".  A hacky solution that Danny Kaplan came up with in submitr is a question formatted as:
```r
question_text(
  "Student Name:",
  answer(NULL, correct = TRUE),
  incorrect = "Ok",
  try_again_button = "Modify your answer",
  allow_retry = TRUE
)
```
which does work but my hope was to work through something more general since I think including questions and exercises without feedback would be useful.

**Comment by caievelyn** [comment]
I had previously looked at the submitr package for recording responses, but didn't know about question_text. I do like the idea of using a learnr question for students to submit their names so it's included in the hash. Thank you for the suggest!

Just for reference, here's the code I have that collects the name+hash and creates a download output:

```{r context="setup"}
fluidPage(
    mainPanel(
          div(id = "form",
            textInput("name", "Name", ""),
            textInput("hash", "Hash", ""),
            actionButton("submit", "Submit", class = "btn-primary"),
            downloadButton("downloadData", "Download")
          )
        )
    )
```

```{r context="server"}

learnrhash::encoder_logic()
 observeEvent(input$submit,{
        name_id <<- input$name
        hash_id <<- input$hash
        responses <<- data.frame("Name" = name_id, "Hash" = hash_id)
 })
output$downloadData <- downloadHandler(
      filename = "responses.rds",
      content = function(file) {
      write_rds(responses, file)
    }
  )
```
